### ISSUE TITLE
PassFF button sometimes invisible

### ISSUE THREAD

**Issue by muesli4** [nwallace/passff#108] opened 2015-10-17 10:56 UTC
More often than not, the passff icon is hidden when starting firefox and the shortcut does not work. I can make it work again with deactivating and activating in about:addons.

This happend already some versions earlier (but still there in 41.0.1).

**Comment by sometoby** [comment] 2015-10-30 12:47
I can't reproduce this problem. There is a similar problem with the Firefox Developer Edition, where the PassFF action button will consistently disappear when you deactivate Firefox' browsing history. Is your browsing history deactivated?

**Comment by muesli4** [comment] 2015-10-30 13:35
No. But with firefox version 41.0.2 it works again (always showing, until now).

**Comment by sometoby** [comment] 2015-11-02 02:18
Then I'll close this issue for now. Reopen it if the problem comes back.

**Comment by muesli4** [comment] 2015-12-19 12:14
I'm using firefox 42.0 and I found that I'm still having the issue. I looked into the browser console and found the following:

```
1450527027803	addons.xpi	WARN	Exception running bootstrap method shutdown on passff@invicem.pro: [Exception... "Component returned failure code: 0x80070057 (NS_ERROR_ILLEGAL_VALUE) [nsIDOMWindowUtils.removeSheet]"  nsresult: "0x80070057 (NS_ERROR_ILLEGAL_VALUE)"  location: "JS frame :: resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/moritz/.mozilla/firefox/abqx3orx.Default%20User/extensions/passff@invicem.pro.xpi!/bootstrap.js :: PassFF.windowListener.removeUI :: line 274"  data: no] Stack trace: PassFF.windowListener.removeUI()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/moritz/.mozilla/firefox/abqx3orx.Default%20User/extensions/passff@invicem.pro.xpi!/bootstrap.js:274 < PassFF.uninit()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/moritz/.mozilla/firefox/abqx3orx.Default%20User/extensions/passff@invicem.pro.xpi!/bootstrap.js:194 < shutdown()@resource://gre/modules/addons/XPIProvider.jsm -> jar:file:///home/moritz/.mozilla/firefox/abqx3orx.Default%20User/extensions/passff@invicem.pro.xpi!/bootstrap.js:72 < XPI_callBootstrapMethod()@resource://gre/modules/addons/XPIProvider.jsm:4774 < XPI_updateAddonDisabledState()@resource://gre/modules/addons/XPIProvider.jsm:4900 < AddonWrapper_userDisabledSetter()@resource://gre/modules/addons/XPIProvider.jsm:7260 < set_userDisabled()@addonversion.xml:344 < oncommand()@about:addons:1 < <file:unknown>
```

**Comment by JumpingSpottedTiger** [comment] 2016-10-31 15:08
This is still an issue for me. Here are my addons:

```
Asynchronous Plugin Rendering	2.0	true	asyncrendering@mozilla.org
Decentraleyes	1.3.5	true	jid1-BoFifL9Vbdl2zQ@jetpack
GNotifier	1.9.8	true	jid1-OoNOA6XBjznvLQ@jetpack
HTTPS Everywhere	5.2.6	true	https-everywhere-eff@eff.org
Multi-process staged rollout	1.3	true	e10srollout@mozilla.org
No Close Buttons	0.1.1-signed.1-signed	true	no-close-buttons@xavamedia.nl
NoScript	2.9.0.14	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
PassFF	0.1.32	true	passff@invicem.pro
PentadactylSigned	7296	true	pentadactyl-signed@willsalmanj.github.com
Self-Destructing Cookies	0.4.11	true	jid0-9XfBwUWnvPx4wWsfBWMCm4Jj69E@jetpack
Tree Style Tab	0.18.2016090802	true	treestyletab@piro.sakura.ne.jp
uBlock Origin	1.9.16	true	uBlock0@raymondhill.net
Web Compat	1.0	true	webcompat@mozilla.org
LastPass	4.1.29a	false	support@lastpass.com
Pocket	1.0.4	false	firefox@getpocket.com
```

@muesli4 Does this still affect you, too? Do you have the ability to reopen it?

**Comment by muesli4** [comment] 2016-11-01 13:26
@JumpingSpottedTiger No, at the moment it works fine for me with Firefox 49.0.2.

**Comment by nwallace** [comment] 2016-11-02 02:32
@JumpingSpottedTiger Is the button hidden every time you restart your browser, or is just once in a while?  I've seen this myself occasionally, but not consistently.

Maybe an improvement to error-handling would help.  Even if there's a problem at startup, it would be better to at least see the error.

**Comment by JumpingSpottedTiger** [comment] 2016-11-02 14:15
It's typically just once in a while. It may or may not happen when I restart the browser as well but I'm never looking. I'll keep my eye out for it but as I have my computer and browser open for weeks at a time it's definitely 'mid-session' that I notice it the most.

**Comment by jfeick** [comment] 2016-11-02 17:00
I'm experiencing the same issue with firefox-aurora on arch linux (Firefox 51.0.a2)
I have to visit about:addons first and manually disable and enable passff.

Is there any way to gather more information?

**Comment by nwallace** [comment] 2016-11-03 00:18
@jfeick There's a preference to enable logging (see [this section of the README](https://github.com/nwallace/passff#see-the-logs)), but you'll have to go to about:config and set 'extensions.logging.enabled' to true as well.

Although, now that I say that, I'm trying it myself and I don't see the logging. Is it working for you?

**Comment by jfeick** [comment] 2016-11-03 10:58
@nwallace Logging is working now. Logs appear on stdout if I launch firefox-aurora from Terminal.
The bug is gone at the moment and I cannot reproduce it at the moment!?! I will update this issue with logs as soon as the behaviour shows again.

**Comment by jfeick** [comment] 2016-11-03 11:26
@nwallace I disabled all addons except passff and started up firefox several times. The erroneous behaviour happens when firefox is restarting from sessionstore.js.
Attached is a complete log. (I cropped some information about my installed addons for privacy reasons - but none have been enabled)
[passfflog.txt](https://github.com/nwallace/passff/files/568795/passfflog.txt)

**Comment by nwallace** [comment] 2016-12-11 18:39
Thanks @jfeick . I'm looking into this.

**Comment by tuxor1337** [comment] 2017-04-08 14:50
Please reopen if this still applies to the latest version from Github.

**Closed by tuxor1337** 2017-04-08 14:50 UTC
Labels: bug
