### ISSUE TITLE
Empty fields on second firefox window

### ISSUE THREAD

**Issue by yulimoto** [nwallace/passff#187] opened 2017-03-13 10:10 UTC
How to reproduce issue 
1. Open firefox with passff enabled (everything works fine) . it is first window
2. Open new firefox window (not tab) . it is second window
3. goto passff icon on second window and click it two or more times. Probably first time will be ok, but when you click it second, third and so on will shows empty fields

I found this bug on FF 41, 45 on linux systems (Slackware, Debian, Ubuntu)

**Comment by tuxor1337** [comment] 2017-03-13 10:18
Duplicate of https://github.com/nwallace/passff/issues/131, will be fixed with WebExtensions.

**Closed by tuxor1337** 2017-03-13 10:18 UTC
Labels: duplicate
