### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by dhowe** [nwallace/passff#93] opened 2015-07-26 15:10 UTC
Not sure what is causing what here. I get alerted to the error below when I click directly on the passff XPI in github, however the plugin _appears_ to install anyway. When I remove the original installation via the addon manager, then download the .xpi file, then install by dragging into the manager, things seems to work correctly thereafter, no further errors, but there is no passff menu button visible (nor available in the toolbar 'customize' view)

```
Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIFile.isExecutable]

OSX 10.10.3 (14D136) / FF 39.0
```

**Comment by jvenant** [comment] 2015-07-26 15:20
Could you try with an other / new Firefox profile ?

**Comment by dhowe** [comment] 2015-07-26 15:23
Same error with a newly created FF-profile, this time just dragging the downloaded file into the addon manager:

![screen shot 2015-07-26 at 11 22 18 pm](https://cloud.githubusercontent.com/assets/737638/8894551/40d3cbb8-33ed-11e5-979f-49eeda598717.png)

**Comment by dhowe** [comment] 2015-07-26 15:26
Note: on this install, when I open the preferences, I can make changes within, however I cannot return to other browser functions; the preferences tab is stuck open, and I cannot close the tab or switch to any other.

**Comment by dhowe** [comment] 2015-07-26 15:27
![screen shot 2015-07-26 at 11 26 48 pm](https://cloud.githubusercontent.com/assets/737638/8894565/d1c08562-33ed-11e5-910a-aeabc80e097d.png)

**Comment by jvenant** [comment] 2015-07-26 15:29
could you try installing v1-pre-release-24 ?

**Comment by dhowe** [comment] 2015-07-26 15:32
That one seems to work correctly -- no error on install, and the passff button opens with my password keys pre-populated...

**Comment by jvenant** [comment] 2015-07-26 15:38
could you try to test each version from there and tell me when the bug appear

@sometoby : any idea ?

**Comment by dhowe** [comment] 2015-07-26 15:38
I'm guessing the error's coming from somewhere in getCommandStr in passff/src/chrome/content/subprocess.jsm (~line 371), maybe a try/catch in there would help narrow it down...

**Comment by dhowe** [comment] 2015-07-26 15:42
Error appears first in rv1-pre-release-25

**Comment by jvenant** [comment] 2015-07-26 15:45
could you go to the about:config location, filter on passff and check that the extentions.passff.command value match your pass script location

**Comment by dhowe** [comment] 2015-07-26 15:47
Ok, so I also get that error when I hit 'refresh' in the menu button. However, it goes away when I correct the path in about:config -- changed from /usr/bin/pass to /usr/local/bin/pass

**Comment by jvenant** [comment] 2015-07-26 15:48
does the very last version work now using the good pass location ?

**Comment by dhowe** [comment] 2015-07-26 15:51
Well, it seems to at first, after that change... but the preferences window still gets stuck open (perhaps this is a separate issue?) and then I can't do anything unless I restart the browser.

**Comment by jvenant** [comment] 2015-07-26 16:07
probably you should use the  v1-pre-release-24 for now.
I hope @sometoby will have an idea because I can't reproduce this behaviour on my arch

**Comment by sometoby** [comment] 2015-07-26 16:15
This behavior is, unfortunately, expected. PassFF uses /usr/bin/pass as the default script path and tries to execute it when first installed to gather a list of password entries. Assuming you installed pass via homebrew, setting the script location to /usr/local/bin/pass as you already have should solve your problem.

A possible solution would be what I suggested in #72: Have defaults that match the setup most users are likely to have.

**Comment by sometoby** [comment] 2015-07-26 16:16
All of the other weirdness that happens when the pass script can't be executed should of course be handled properly. I will look into that later today.

**Comment by sometoby** [comment] 2015-07-26 16:18
Regarding the preference window being stuck open, does closing it with Command+W not work?

Adding a proper close button might be prudent.

**Comment by jvenant** [comment] 2015-07-26 16:20
but event using the good location, the preference dialog seems to still have some wired behaviour

**Comment by dhowe** [comment] 2015-07-26 20:05
Just to follow-up, ctrl-w does not work to close the stuck preference manager. Regarding the expected path, I used homebrew to install pass, which is pretty standard these days, but of course there will always be different paths for some portion of users. If you can catch that error, then you might a) try multiple locations, and/or b) pop up a dialog box where users can enter the right path, or even c) try 'which' or equivalent (though I'm not sure if this is allowed from an extension)

**Comment by sometoby** [comment] 2015-07-26 20:32
I think you either misread or mistyped - I didn't mean Ctrl, but the command (⌘) key.

Does ⌘+W close the preferences dialog? It does so for me.

**Comment by dhowe** [comment] 2015-07-27 00:16
Yes, that works, though manually closing the tab does not...

**Comment by sometoby** [comment] 2015-07-27 00:24
I do think that this is normal behavior for a modal dialog. On OS X, Firefox’ placement of the dialog window makes it a little unclear it is actually on top of and blocking everything else.

**Comment by dhowe** [comment] 2015-07-27 00:31
But a modal dialog closes when you enter whatever it is asking for.

**Comment by sometoby** [comment] 2015-07-27 00:48
Normally this would be the case, but the PassFF preferences window isn't a dialog in the classical sense, but rather a bunch of tabs with UI elements in them, thrown into a dialog box.

We should probably just use a normal window instead. It would make it much easier to look things up while keeping the preferences window open.

**Comment by jgillich** [comment] 2015-11-10 02:47
I also have the same issue on NixOS, where the actual binary is somewhere entirely different. What about `/usr/bin/env pass`? It should point to the correct binary on any system. Although currently that returns the same error, but that might be fixable..

**Comment by otwieracz** [comment] 2016-01-26 20:10
Same issue here on NixOS.

**Comment by Philelis** [comment] 2016-04-11 19:13
I had the same error, for me it helps to fix the config to the right paths and using shell (OSX).

**Comment by zeckalpha** [comment] 2016-04-25 00:32
I was able to install using `sudo ln -s /usr/local/bin/pass /usr/bin/pass`, however the menu doesn't appear and the key combination don't seem to do anything. Opening the preferences and playing around with them don't seem to help

**Comment by jgillich** [comment] 2016-04-27 18:06
@zeckalpha Just open the passff config and enter the path there ("Pass command" under "Pass Script").

**Comment by tuxor1337** [comment] 2017-04-08 14:54
Please reopen if this still applies to the latest version from Github.

**Closed by tuxor1337** 2017-04-08 14:54 UTC
Labels: bug
