### ISSUE TITLE
Pass store dir is reset after Firefox restarted

### ISSUE THREAD

**Issue by MathiasRenner** [nwallace/passff#177] opened 2016-12-05 21:19 UTC
In order to define the pass store directory, I define it in the preferences of PassFF. It works fine as long as Firefox is running.

However, after a restart, PassFF forgets this setting and I have to put it in again. How can set this permanent?

It's Firefox (latest) on Ubuntu 16.04.

**Comment by MathiasRenner** [comment] 2016-12-05 21:28
If I manually add this setting to `preferences.js` in `modules` inside of `~/.mozilla/firefox/<profile>/extensions/passff@invicem.pro.xpi`, Firefox disables the add-on due to a verification error. 

Probably the checksum is broken then. So this workaround does not work.

**Comment by nwallace** [comment] 2016-12-16 04:24
Sorry to hear you're having issues. Setting the preference should automatically persist between browser sessions (that's how Firefox handles extension preferences), so I'm not sure what could be going wrong.

Fortunately, I've got a big re-write I'm trying to release in the next few weeks, and hopefully that will address this issue.

**Comment by nwallace** [comment] 2016-12-16 04:34
Closing as a duplicate of https://github.com/nwallace/passff/issues/152, but if you've got more to ask or add, please do so!

**Closed by nwallace** 2016-12-16 04:34 UTC
Labels: duplicate
