### ISSUE TITLE
window does not appear when docked in liberator toolbar

### ISSUE THREAD

**Issue by jimdigriz** [nwallace/passff#113] opened 2015-10-31 10:51 UTC
I used the Vimperator plugin which gives me a toolbar at the bottom of my screen to dock into, this lets me save a whole lot of screen real estate space.  The problem is that when I dock the passff icon in the 'liberator' toolbar, when I click on the icon, the popup window does not appear.

This was a very similar bug I experienced and reported in https://github.com/gorhill/uBlock/issues/797, I suspect that the window is being rendered off screen to the bottom.

Attached are some 'in action' screenshots:

![works fine when in the navigator slot](https://cloud.githubusercontent.com/assets/2567406/10863176/8819cba6-7fbc-11e5-9c3b-59ad2e2e86fe.jpeg)

...and when docked in the toolbar in the bottom right (next to ublock and privacy badger):

![when docked in the toolbar, it visibly does nothing](https://cloud.githubusercontent.com/assets/2567406/10863175/87d6c180-7fbc-11e5-8cc7-809bf8b595e2.jpeg)

Interestingly, after docking the icon there initially, it does work, the problem only occurs for new windows I open.  One thing that might be related, is that the toolbar has been configured to be hidden initially (unhidden with F8) with a [.vimperatorrc.local](http://stuff.digriz.org.uk/vimperatorrc.local.txt) script, which might be confusing the plugin.

Let me know if you need any more information.

**Comment by polyzen** [comment] 2015-12-02 22:08
Duplicate of #37

**Comment by tuxor1337** [comment] 2017-04-08 14:49
Please reopen if this still applies to the latest version from Github.

**Closed by tuxor1337** 2017-04-08 14:49 UTC
Labels: duplicate, incompatibility
